name = "hs-code-verifier-api"
compatibility_date = "2024-01-01"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]

account_id = ""  # AUTOMATYCZNIE Z GITHUB SECRETS
workers_dev = true

[vars]
ENVIRONMENT = "production"
VERSION = "1.4.3"
MAX_REQUESTS_PER_DAY = 20000
ALLOWED_ORIGINS = "https://marius-sys.github.io"
SYNC_TOKEN = ""  # WYPEŁNIĆ W CLOUDFLARE
CRON_SECRET = "" # WYPEŁNIĆ W CLOUDFLARE
SANCTIONED_CODES = ""  # Kody 4-cyfrowe oddzielone przecinkami

[[kv_namespaces]]
binding = "HS_DATABASE"
id = "d4e909bdc6114613ab76635fadb855b2"

[triggers]
crons = ["0 3 * * *"]